services:
  - type: web
    name: erp-stock-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: DATABASE_URL
        fromDatabase:
          name: erp-stock-db
          property: connectionString

  - type: web
    name: erp-stock-front
    runtime: static
    plan: free
    autoDeploy: true
    rootDir: cliente/pos-ui
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://erp-stock-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: erp-stock-db
    plan: free
    databaseName: posdb
    user: posuser
